name: Rust

on:   
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/checkout@v2

      - name: Format check
        run: cargo fmt -- --check

      - name: Clippy lint
        run: cargo clippy --all-features --all-targets -- -Dwarnings

      - name: Build
        run: cargo build --all-features --all-targets

      - name: Run all tests except doctests
        run: cargo test --all-features --all-targets
      
      - name: Run all doctests
        run: cargo test --all-features --doc

      - name: Build documentation
        run: cargo doc --all-features --no-deps
